// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package libs

// Injectors from wire_config.go:

func NewConfig() interface{} {
	libsConfigType := ProvideConfigType()
	libsEnvironment := ProvideEnvironment()
	libsConfigFile := ProvideConfigFile()
	v := LoadConfig(libsConfigType, libsEnvironment, libsConfigFile)
	return v
}
